apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: gateway-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
            # --- CAMBIO CLAVE 1: Desactivar Eureka (Para no causar ruido) ---
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_CLOUD_DISCOVERY_ENABLED
              value: "false"
            
            # --- CAMBIO CLAVE 2: Rutas Manuales (Sobrescriben GitHub) ---
            # Ruta 0: Account Service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
              value: "account-service-route"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
              value: "http://account-service:8081" # URL interna de K8s (Nombre del Service)
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
              value: "Path=/api/v1/accounts/**, /api/v1/transactions/**"
            
            # Ruta 1: Investment Service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
              value: "investment-service-route"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
              value: "http://investment-service:8083"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
              value: "Path=/api/v1/investments/**"

            # --- SEGURIDAD ---
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: "http://keycloak:8080/realms/myfinances-realm/protocol/openid-connect/certs"
            # TRUCO: Quitamos ISSUER_URI para evitar validación estricta que falla con localhost
            # Spring validará la firma con las JWK de arriba, que es lo importante.
            
            # --- OBSERVABILIDAD ---
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://zipkin:9411/api/v2/spans"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
