apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: investment-service
  template:
    metadata:
      labels:
        app: investment-service
    spec:
      containers:
        - name: investment-service
          image: investment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
            
            # Base de datos
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-db:5432/investment_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "myfinances_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "myfinances_pass"
            
            # Observabilidad
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://zipkin:9411/api/v2/spans"
            
            # Service URLs
            - name: SERVICES_ACCOUNT_SERVICE_URL
              value: "http://account-service:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: investment-service
spec:
  selector:
    app: investment-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
